/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_freakishfox_xxq_NativeUtil_NativeUtil */

#ifndef _Included_com_freakishfox_xxq_NativeUtil_NativeUtil
#define _Included_com_freakishfox_xxq_NativeUtil_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_freakishfox_xxq_NativeUtil_NativeUtil
 * Method:    printNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_freakishfox_xxq_NativeUtil_NativeUtil_printNative
  (JNIEnv *, jobject);

/*
 * Class:     com_freakishfox_xxq_NativeUtil_NativeUtil
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_freakishfox_xxq_NativeUtil_NativeUtil_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
